---

- name: 'CONFIG | Create email script file'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(root) }}"
    group: "{{ item.group | default(root) }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items: "{{ notify_mail_config }}"


- name: 'CONFIG | Create notify service configuration file'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(root) }}"
    group: "{{ item.group | default(root) }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items: "{{ notify_service_systemd }}"
  register: create_notify_service_config_file

- name: 'CONFIG | Modify systemd service file'
  become: True
  lineinfile:
    dest: "{{ item.dest }}"
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
  with_items: "{{ systemd_notify_options }}"
  notify: 'HANDLER | Restart systemd'
  when: create_notify_service_config_file.changed
