---

# Main tasks file for ansible-role-systemd-notify role

- name: 'INIT | Manage variables to use for our target'
  include_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::systemd-notify'
    - 'role::systemd-notify::init'

- name: 'INSTALL | Install package with lockfile'
  become: True
  include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - 'role::systemd-notify'
    - 'role::systemd-notify::install'

- name: 'CONFIG | Manage config tasks'
  become: 'True'
  include_tasks: "{{ role_path }}/tasks/config.yml"
  tags:
    - 'role::systemd-notify'
    - 'role::systemd-notify::config'
